package core

import (
	"fmt"
	"time"

	"github.com/wowsims/tbc/sim/core/stats"
)

type ApplySpellEffects func(*Simulation, *Target, *Spell)

type SpellConfig struct {
	// See definition of Spell (below) for comments on these.
	ActionID
	SpellSchool  SpellSchool
	SpellExtras  SpellExtras
	ResourceType stats.Stat
	BaseCost     float64

	Cast CastConfig

	ApplyEffects   ApplySpellEffects
	DisableMetrics bool
}

type SpellMetrics struct {
	// Metric totals for this spell, for the current iteration.
	Casts              int32
	Misses             int32
	Hits               int32
	Crits              int32
	Dodges             int32
	Glances            int32
	Parries            int32
	Blocks             int32
	PartialResists_1_4 int32   // 1/4 of the spell was resisted
	PartialResists_2_4 int32   // 2/4 of the spell was resisted
	PartialResists_3_4 int32   // 3/4 of the spell was resisted
	TotalDamage        float64 // Damage done by all casts of this spell.
	TotalThreat        float64 // Threat generated by all casts of this spell.
}

type Spell struct {
	// ID for this spell.
	ActionID

	// The character who will perform this spell.
	Character *Character

	// Fire, Frost, Shadow, etc.
	SpellSchool SpellSchool

	// Flags
	SpellExtras SpellExtras

	// Should be stats.Mana, stats.Energy, stats.Rage, or unset.
	ResourceType stats.Stat

	// Base cost. Many effects in the game which 'reduce mana cost by X%'
	// are calculated using the base cost.
	BaseCost float64

	// Default cast parameters with all static effects applied.
	DefaultCast Cast

	CD       Cooldown
	SharedCD Cooldown

	// Performs a cast of this spell.
	castFn CastSuccessFunc

	SpellMetrics

	ApplyEffects ApplySpellEffects

	// The current or most recent cast data.
	CurCast Cast

	DisableMetrics bool
}

// Registers a new spell to the character. Returns the newly created spell.
func (character *Character) RegisterSpell(config SpellConfig) *Spell {
	if len(character.Spellbook) > 100 {
		panic(fmt.Sprintf("Over 100 registered spells when registering %s! There is probably a spell being registered every iteration.", config.ActionID))
	}

	spell := &Spell{
		ActionID:     config.ActionID,
		Character:    character,
		SpellSchool:  config.SpellSchool,
		SpellExtras:  config.SpellExtras,
		ResourceType: config.ResourceType,
		BaseCost:     config.BaseCost,

		DefaultCast: config.Cast.DefaultCast,
		CD:          config.Cast.CD,
		SharedCD:    config.Cast.SharedCD,

		ApplyEffects:   config.ApplyEffects,
		DisableMetrics: config.DisableMetrics,
	}

	spell.castFn = spell.makeCastFunc(config.Cast, spell.applyEffects)

	character.Spellbook = append(character.Spellbook, spell)

	return spell
}

// Returns the first registered spell with the given ID, or nil if there are none.
func (character *Character) GetSpell(actionID ActionID) *Spell {
	for _, spell := range character.Spellbook {
		if spell.ActionID.SameAction(actionID) {
			return spell
		}
	}
	return nil
}

// Retrieves an existing spell with the same ID as the config uses, or registers it if there is none.
func (character *Character) GetOrRegisterSpell(config SpellConfig) *Spell {
	registered := character.GetSpell(config.ActionID)
	if registered == nil {
		return character.RegisterSpell(config)
	} else {
		return registered
	}
}

// Metrics for the current iteration
func (spell *Spell) CurDamagePerCast() float64 {
	if spell.Casts == 0 {
		return 0
	} else {
		return spell.TotalDamage / float64(spell.Casts)
	}
}

func (spell *Spell) reset(_ *Simulation) {
	spell.SpellMetrics = SpellMetrics{}
}

func (spell *Spell) doneIteration() {
	if !spell.DisableMetrics {
		spell.Character.Metrics.addSpell(spell)
	}
}

func (spell *Spell) IsReady(sim *Simulation) bool {
	return BothTimersReady(spell.CD.Timer, spell.SharedCD.Timer, sim)
}

func (spell *Spell) TimeToReady(sim *Simulation) time.Duration {
	return MaxTimeToReady(spell.CD.Timer, spell.SharedCD.Timer, sim)
}

func (spell *Spell) Cast(sim *Simulation, target *Target) bool {
	return spell.castFn(sim, target)
}

// Skips the actual cast and applies spell effects immediately.
func (spell *Spell) SkipCastAndApplyEffects(sim *Simulation, target *Target) {
	if sim.Log != nil {
		spell.Character.Log(sim, "Casting %s (Cost = %0.03f, Cast Time = %s)",
			spell.ActionID, spell.DefaultCast.Cost, 0)
		spell.Character.Log(sim, "Completed cast %s", spell.ActionID)
	}
	spell.applyEffects(sim, target)
}

func (spell *Spell) applyEffects(sim *Simulation, target *Target) {
	spell.Casts++
	spell.ApplyEffects(sim, target, spell)
}

func ApplyEffectFuncDirectDamage(baseEffect SpellEffect) ApplySpellEffects {
	if baseEffect.BaseDamage.Calculator == nil {
		// Just a hit check.
		return func(sim *Simulation, target *Target, spell *Spell) {
			effect := &baseEffect
			effect.Target = target
			effect.init(sim, spell)

			damage := 0.0
			effect.OutcomeApplier(sim, spell, effect, &damage)
			effect.triggerProcs(sim, spell)
		}
	} else {
		return func(sim *Simulation, target *Target, spell *Spell) {
			effect := &baseEffect
			effect.Target = target
			effect.init(sim, spell)

			damage := effect.calculateBaseDamage(sim, spell) * effect.DamageMultiplier
			effect.calcDamageSingle(sim, spell, damage)
			effect.finalize(sim, spell)
		}
	}
}

func ApplyEffectFuncDirectDamageTargetModifiersOnly(baseEffect SpellEffect) ApplySpellEffects {
	return func(sim *Simulation, target *Target, spell *Spell) {
		effect := &baseEffect
		effect.Target = target

		damage := effect.calculateBaseDamage(sim, spell) * effect.DamageMultiplier
		effect.calcDamageTargetOnly(sim, spell, damage)
		effect.finalize(sim, spell)
	}
}

func ApplyEffectFuncDamageMultiple(baseEffects []SpellEffect) ApplySpellEffects {
	if len(baseEffects) == 0 {
		panic("Multiple damage requires hits")
	} else if len(baseEffects) == 1 {
		return ApplyEffectFuncDirectDamage(baseEffects[0])
	}

	return func(sim *Simulation, _ *Target, spell *Spell) {
		for i := range baseEffects {
			effect := &baseEffects[i]
			effect.init(sim, spell)
			damage := effect.calculateBaseDamage(sim, spell) * effect.DamageMultiplier
			effect.calcDamageSingle(sim, spell, damage)
		}
		for i := range baseEffects {
			effect := &baseEffects[i]
			effect.finalize(sim, spell)
		}
	}
}
func ApplyEffectFuncDamageMultipleTargeted(baseEffects []SpellEffect) ApplySpellEffects {
	if len(baseEffects) == 0 {
		panic("Multiple damage requires hits")
	} else if len(baseEffects) == 1 {
		return ApplyEffectFuncDirectDamage(baseEffects[0])
	}

	return func(sim *Simulation, target *Target, spell *Spell) {
		for i := range baseEffects {
			effect := &baseEffects[i]
			effect.Target = target
			effect.init(sim, spell)
			damage := effect.calculateBaseDamage(sim, spell) * effect.DamageMultiplier
			effect.calcDamageSingle(sim, spell, damage)
		}
		for i := range baseEffects {
			effect := &baseEffects[i]
			effect.finalize(sim, spell)
		}
	}
}
func ApplyEffectFuncAOEDamage(sim *Simulation, baseEffect SpellEffect) ApplySpellEffects {
	numHits := sim.GetNumTargets()
	effects := make([]SpellEffect, numHits)
	for i := int32(0); i < numHits; i++ {
		effects[i] = baseEffect
		effects[i].Target = sim.GetTarget(i)
	}
	return ApplyEffectFuncDamageMultiple(effects)
}

func ApplyEffectFuncDot(dot *Dot) ApplySpellEffects {
	return func(sim *Simulation, _ *Target, _ *Spell) {
		dot.Apply(sim)
	}
}

func applyAOECap(effects []SpellEffect, aoeCap float64) {
	// Increased damage from crits doesn't count towards the cap, so need to
	// tally pre-crit damage.
	totalTowardsCap := 0.0
	for i, _ := range effects {
		effect := &effects[i]
		totalTowardsCap += effect.Damage
	}

	if totalTowardsCap <= aoeCap {
		return
	}

	maxDamagePerHit := aoeCap / float64(len(effects))
	for i, _ := range effects {
		effect := &effects[i]
		damageTowardsCap := effect.Damage
		if damageTowardsCap > maxDamagePerHit {
			effect.Damage -= damageTowardsCap - maxDamagePerHit
		}
	}
}
