import { ActionID as ActionIdProto } from '/tbc/core/proto/common.js';
import { Item } from '/tbc/core/proto/common.js';
import { OtherAction } from '/tbc/core/proto/common.js';
export declare class ActionId {
    readonly itemId: number;
    readonly spellId: number;
    readonly otherId: OtherAction;
    readonly tag: number;
    readonly name: string;
    readonly iconUrl: string;
    private constructor();
    equals(other: ActionId): boolean;
    equalsIgnoringTag(other: ActionId): boolean;
    setBackground(elem: HTMLElement): void;
    setWowheadHref(elem: HTMLAnchorElement): void;
    setBackgroundAndHref(elem: HTMLAnchorElement): void;
    fillAndSet(elem: HTMLAnchorElement, setHref: boolean, setBackground: boolean): Promise<ActionId>;
    private static getTooltipDataHelper;
    private getTooltipData;
    fill(playerIndex?: number): Promise<ActionId>;
    toString(): string;
    toProto(): ActionIdProto;
    toProtoString(): string;
    static fromEmpty(): ActionId;
    static fromItemId(itemId: number, tag?: number): ActionId;
    static fromSpellId(spellId: number, tag?: number): ActionId;
    static fromOtherId(otherId: OtherAction, tag?: number): ActionId;
    static fromItem(item: Item): ActionId;
    static fromProto(protoId: ActionIdProto): ActionId;
    static fromLogString(str: string): ActionId;
}
