import { Gem } from '/tbc/core/proto/common.js';
import { GemColor } from '/tbc/core/proto/common.js';
export declare function gemMatchesSocket(gem: Gem, socketColor: GemColor): boolean;
export declare function gemEligibleForSocket(gem: Gem, socketColor: GemColor): boolean;
export declare class MetaGemCondition {
    readonly id: number;
    readonly description: string;
    readonly minRed: number;
    readonly minYellow: number;
    readonly minBlue: number;
    readonly compareColorGreater: GemColor;
    readonly compareColorLesser: GemColor;
    constructor(id: number, description: string, minRed: number, minYellow: number, minBlue: number, compareColorGreater: GemColor, compareColorLesser: GemColor);
    isMet(numRed: number, numYellow: number, numBlue: number): boolean;
    private static getNumInCategory;
    static fromMinColors(id: number, description: string, minRed: number, minYellow: number, minBlue: number): MetaGemCondition;
    static fromCompareColors(id: number, description: string, compareColorGreater: GemColor, compareColorLesser: GemColor): MetaGemCondition;
}
export declare function getMetaGemCondition(id: number): MetaGemCondition;
export declare function isMetaGemActive(metaGem: Gem, numRed: number, numYellow: number, numBlue: number): boolean;
export declare function getMetaGemConditionDescription(metaGem: Gem): string;
export declare const BRUTAL_EARTHSTORM_DIAMOND: MetaGemCondition;
export declare const CHAOTIC_SKYFIRE_DIAMOND: MetaGemCondition;
export declare const DESTRUCTIVE_SKYFIRE_DIAMOND: MetaGemCondition;
export declare const EMBER_SKYFIRE_DIAMOND: MetaGemCondition;
export declare const ETERNAL_EARTHSTORM_DIAMOND: MetaGemCondition;
export declare const IMBUED_UNSTABLE_DIAMOND: MetaGemCondition;
export declare const INSIGHTFUL_EARTHSTORM_DIAMOND: MetaGemCondition;
export declare const POWERFUL_EARTHSTORM_DIAMOND: MetaGemCondition;
export declare const RELENTLESS_EARTHSTORM_DIAMOND: MetaGemCondition;
export declare const SWIFT_SKYFIRE_DIAMOND: MetaGemCondition;
export declare const SWIFT_STARFIRE_DIAMOND: MetaGemCondition;
export declare const SWIFT_WINDFIRE_DIAMOND: MetaGemCondition;
export declare const TENACIOUS_EARTHSTORM_DIAMOND: MetaGemCondition;
export declare const THUNDERING_SKYFIRE_DIAMOND: MetaGemCondition;
export declare const BRACING_EARTHSTORM_DIAMOND: MetaGemCondition;
export declare const ENIGMATIC_SKYFIRE_DIAMOND: MetaGemCondition;
export declare const MYSTICAL_SKYFIRE_DIAMOND: MetaGemCondition;
export declare const POTENT_UNSTABLE_DIAMOND: MetaGemCondition;
export declare function setGemSocketCssClass(elem: HTMLElement, color: GemColor): void;
export declare function getEmptyGemSocketIconUrl(color: GemColor): string;
