import { Class } from '/tbc/core/proto/common.js';
import { ItemSlot } from '/tbc/core/proto/common.js';
import { Race } from '/tbc/core/proto/common.js';
import { Stat } from '/tbc/core/proto/common.js';
import { ResourceType } from '/tbc/core/proto/api.js';
export declare const raceNames: Record<Race, string>;
export declare function nameToRace(name: string): Race;
export declare const classNames: Record<Class, string>;
export declare function nameToClass(name: string): Class;
export declare const statOrder: Array<Stat>;
export declare const statNames: Record<Stat, string>;
export declare const slotNames: Record<ItemSlot, string>;
export declare const resourceNames: Record<ResourceType, string>;
export declare const resourceColors: Record<ResourceType, string>;
export declare function stringToResourceType(str: string): ResourceType;
