import { RaidBuffs } from '/tbc/core/proto/common.js';
import { PartyBuffs } from '/tbc/core/proto/common.js';
import { IndividualBuffs } from '/tbc/core/proto/common.js';
import { Consumes } from '/tbc/core/proto/common.js';
import { Encounter } from '/tbc/core/proto/common.js';
import { Race } from '/tbc/core/proto/common.js';
import { Spec } from '/tbc/core/proto/common.js';
import { ComputeStatsRequest } from '/tbc/core/proto/api.js';
import { IndividualSimRequest } from '/tbc/core/proto/api.js';
import { Gear } from './gear.js';
import { Stats } from './stats.js';
import { SpecRotation } from './utils.js';
import { SpecTalents } from './utils.js';
import { SpecOptions } from './utils.js';
export declare function makeComputeStatsRequest<SpecType extends Spec>(raidBuffs: RaidBuffs, partyBuffs: PartyBuffs, individualBuffs: IndividualBuffs, consumes: Consumes, customStats: Stats, encounter: Encounter, gear: Gear, race: Race, rotation: SpecRotation<SpecType>, talents: SpecTalents<SpecType>, classOptions: SpecOptions<SpecType>): ComputeStatsRequest;
export declare function makeIndividualSimRequest<SpecType extends Spec>(raidBuffs: RaidBuffs, partyBuffs: PartyBuffs, individualBuffs: IndividualBuffs, consumes: Consumes, customStats: Stats, encounter: Encounter, gear: Gear, race: Race, rotation: SpecRotation<SpecType>, talents: SpecTalents<SpecType>, classOptions: SpecOptions<SpecType>, iterations: number, debug: boolean): IndividualSimRequest;
