// +build balance_druid

// DO NOT EDIT. This file is auto-generated by the item generator tool. Use that to make edits.

package items

import (
	"github.com/wowsims/tbc/sim/api"
	"github.com/wowsims/tbc/sim/core/stats"
)

var items = []Item{}
