export const CHARACTER_LEVEL = 70;
export const BOSS_LEVEL = CHARACTER_LEVEL + 3;
export const EXPERTISE_PER_QUARTER_PERCENT_REDUCTION = 3.94;
export const MELEE_CRIT_RATING_PER_CRIT_CHANCE = 22.08;
export const MELEE_HIT_RATING_PER_HIT_CHANCE = 15.77;
export const SPELL_CRIT_RATING_PER_CRIT_CHANCE = 22.08;
export const SPELL_HIT_RATING_PER_HIT_CHANCE = 12.62;
export const HASTE_RATING_PER_HASTE_PERCENT = 15.77;
