# syntax=docker/dockerfile:1

FROM golang:1.16

WORKDIR /tbc

RUN apt-get update
RUN apt-get install -y protobuf-compiler
RUN go get -u -v github.com/golang/protobuf/proto
RUN go get -u -v github.com/golang/protobuf/protoc-gen-go
