import { Item } from './proto/common.js';
import { ItemSlot } from './proto/common.js';
import { ActionId, ItemOrSpellId, RawActionId } from '/tbc/core/proto_utils/action_id.js';
export declare const specDirectory: string;
export declare function getEmptySlotIconUrl(slot: ItemSlot): string;
export declare function getTooltipData(id: ItemOrSpellId): Promise<any>;
export declare function getIconUrl(id: RawActionId): Promise<string>;
export declare function getItemIconUrl(item: Item): Promise<string>;
export declare function getName(id: RawActionId): Promise<string>;
export declare function getFullActionName(actionId: ActionId, playerIndex?: number): Promise<string>;
export declare function setWowheadHref(elem: HTMLAnchorElement, id: RawActionId): void;
export declare function setWowheadItemHref(elem: HTMLAnchorElement, item: Item): void;
