import { Buffs } from '/tbc/core/proto/common.js';
import { Consumes } from '/tbc/core/proto/common.js';
import { Enchant } from '/tbc/core/proto/common.js';
import { Encounter } from '/tbc/core/proto/common.js';
import { EquipmentSpec } from '/tbc/core/proto/common.js';
import { Gem } from '/tbc/core/proto/common.js';
import { GemColor } from '/tbc/core/proto/common.js';
import { ItemSlot } from '/tbc/core/proto/common.js';
import { ItemSpec } from '/tbc/core/proto/common.js';
import { Item } from '/tbc/core/proto/common.js';
import { Race } from '/tbc/core/proto/common.js';
import { Spec } from '/tbc/core/proto/common.js';
import { Stat } from '/tbc/core/proto/common.js';
import { ComputeStatsResult } from '/tbc/core/proto/api.js';
import { IndividualSimRequest } from '/tbc/core/proto/api.js';
import { StatWeightsRequest, StatWeightsResult } from '/tbc/core/proto/api.js';
import { EquippedItem } from '/tbc/core/proto_utils/equipped_item.js';
import { Gear } from '/tbc/core/proto_utils/gear.js';
import { Stats } from '/tbc/core/proto_utils/stats.js';
import { SpecRotation } from '/tbc/core/proto_utils/utils.js';
import { SpecTalents } from '/tbc/core/proto_utils/utils.js';
import { SpecTypeFunctions } from '/tbc/core/proto_utils/utils.js';
import { SpecOptions } from '/tbc/core/proto_utils/utils.js';
import { TypedEvent } from './typed_event.js';
import { WorkerPool } from './worker_pool.js';
export interface SimConfig<SpecType extends Spec> {
    spec: Spec;
    epStats: Array<Stat>;
    epReferenceStat: Stat;
    defaults: {
        phase: number;
        gear: EquipmentSpec;
        epWeights: Stats;
        encounter: Encounter;
        buffs: Buffs;
        consumes: Consumes;
        rotation: SpecRotation<SpecType>;
        talents: string;
        specOptions: SpecOptions<SpecType>;
    };
    metaGemEffectEP?: ((gem: Gem, sim: Sim<SpecType>) => number);
}
export declare class Sim<SpecType extends Spec> extends WorkerPool {
    readonly spec: Spec;
    readonly phaseChangeEmitter: TypedEvent<void>;
    readonly buffsChangeEmitter: TypedEvent<void>;
    readonly consumesChangeEmitter: TypedEvent<void>;
    readonly customStatsChangeEmitter: TypedEvent<void>;
    readonly encounterChangeEmitter: TypedEvent<void>;
    readonly gearChangeEmitter: TypedEvent<void>;
    readonly raceChangeEmitter: TypedEvent<void>;
    readonly rotationChangeEmitter: TypedEvent<void>;
    readonly talentsChangeEmitter: TypedEvent<void>;
    readonly talentsStringChangeEmitter: TypedEvent<void>;
    readonly specOptionsChangeEmitter: TypedEvent<void>;
    readonly changeEmitter: TypedEvent<void>;
    readonly gearListEmitter: TypedEvent<void>;
    readonly characterStatsEmitter: TypedEvent<void>;
    private _currentStats;
    private _items;
    private _enchants;
    private _gems;
    private _phase;
    private _buffs;
    private _consumes;
    private _customStats;
    private _gear;
    private _encounter;
    private _race;
    private _rotation;
    private _talents;
    private _talentsString;
    private _specOptions;
    private _epWeights;
    readonly specTypeFunctions: SpecTypeFunctions<SpecType>;
    private readonly _metaGemEffectEP;
    private _init;
    private readonly _defaultGear;
    constructor(config: SimConfig<SpecType>);
    init(): Promise<void>;
    statWeights(request: StatWeightsRequest): Promise<StatWeightsResult>;
    private updateCharacterStats;
    getCurrentStats(): ComputeStatsResult;
    getItems(slot: ItemSlot | undefined): Array<Item>;
    getEnchants(slot: ItemSlot | undefined): Array<Enchant>;
    getGems(socketColor: GemColor | undefined): Array<Gem>;
    getMatchingGems(socketColor: GemColor): Array<Gem>;
    getPhase(): number;
    setPhase(newPhase: number): void;
    getRace(): Race;
    setRace(newRace: Race): void;
    getBuffs(): Buffs;
    setBuffs(newBuffs: Buffs): void;
    getConsumes(): Consumes;
    setConsumes(newConsumes: Consumes): void;
    getEncounter(): Encounter;
    setEncounter(newEncounter: Encounter): void;
    equipItem(slot: ItemSlot, newItem: EquippedItem | null): void;
    getEquippedItem(slot: ItemSlot): EquippedItem | null;
    getGear(): Gear;
    setGear(newGear: Gear): void;
    getCustomStats(): Stats;
    setCustomStats(newCustomStats: Stats): void;
    getRotation(): SpecRotation<SpecType>;
    setRotation(newRotation: SpecRotation<SpecType>): void;
    setTalents(newTalents: SpecTalents<SpecType>): void;
    getTalentsString(): string;
    setTalentsString(newTalentsString: string): void;
    getSpecOptions(): SpecOptions<SpecType>;
    setSpecOptions(newSpecOptions: SpecOptions<SpecType>): void;
    lookupItemSpec(itemSpec: ItemSpec): EquippedItem | null;
    lookupEquipmentSpec(equipSpec: EquipmentSpec): Gear;
    computeGemEP(gem: Gem): number;
    computeEnchantEP(enchant: Enchant): number;
    computeItemEP(item: Item): number;
    makeCurrentIndividualSimRequest(iterations: number, debug: boolean): IndividualSimRequest;
    setWowheadData(equippedItem: EquippedItem, elem: HTMLElement): void;
    toJson(): Object;
    fromJson(obj: any): void;
}
