import { Buffs } from '/tbc/core/proto/common.js';
import { Consumes } from '/tbc/core/proto/common.js';
import { Encounter } from '/tbc/core/proto/common.js';
import { Race } from '/tbc/core/proto/common.js';
import { Spec } from '/tbc/core/proto/common.js';
import { ComputeStatsRequest } from '/tbc/core/proto/api.js';
import { IndividualSimRequest } from '/tbc/core/proto/api.js';
import { Gear } from './gear.js';
import { Stats } from './stats.js';
import { SpecAgent } from './utils.js';
import { SpecTalents } from './utils.js';
import { SpecOptions } from './utils.js';
export declare function makeComputeStatsRequest<SpecType extends Spec>(buffs: Buffs, consumes: Consumes, customStats: Stats, encounter: Encounter, gear: Gear, race: Race, agent: SpecAgent<SpecType>, talents: SpecTalents<SpecType>, classOptions: SpecOptions<SpecType>): ComputeStatsRequest;
export declare function makeIndividualSimRequest<SpecType extends Spec>(buffs: Buffs, consumes: Consumes, customStats: Stats, encounter: Encounter, gear: Gear, race: Race, agent: SpecAgent<SpecType>, talents: SpecTalents<SpecType>, classOptions: SpecOptions<SpecType>, iterations: number, debug: boolean): IndividualSimRequest;
