import { Party } from '/tbc/core/party.js';
import { Player } from '/tbc/core/player.js';
import { Raid } from '/tbc/core/raid.js';
import { Target } from '/tbc/core/target.js';
import { IconInput } from './icon_picker.js';
export declare const ArcaneBrilliance: IconInput<Raid>;
export declare const DivineSpirit: IconInput<Raid>;
export declare const GiftOfTheWild: IconInput<Raid>;
export declare const AtieshMage: IconInput<Party>;
export declare const AtieshWarlock: IconInput<Party>;
export declare const Bloodlust: IconInput<Party>;
export declare const BraidedEterniumChain: IconInput<Party>;
export declare const ChainOfTheTwilightOwl: IconInput<Party>;
export declare const DraeneiRacialCaster: IconInput<Party>;
export declare const DraeneiRacialMelee: IconInput<Party>;
export declare const EyeOfTheNight: IconInput<Party>;
export declare const JadePendantOfBlasting: IconInput<Party>;
export declare const ManaSpringTotem: IconInput<Party>;
export declare const MoonkinAura: IconInput<Party>;
export declare const TotemOfWrath: IconInput<Party>;
export declare const WrathOfAirTotem: IconInput<Party>;
export declare const DrumsOfBattleBuff: IconInput<Party>;
export declare const DrumsOfRestorationBuff: IconInput<Party>;
export declare const BlessingOfKings: IconInput<Player<any>>;
export declare const BlessingOfWisdom: IconInput<Player<any>>;
export declare const ManaTideTotem: IconInput<Player<any>>;
export declare const ImprovedSealOfTheCrusader: IconInput<Target>;
export declare const JudgementOfWisdom: IconInput<Target>;
export declare const Misery: IconInput<Target>;
export declare const CurseOfElements: IconInput<Target>;
export declare const AdeptsElixir: IconInput<Player<any>>;
export declare const BlackenedBasilisk: IconInput<Player<any>>;
export declare const BrilliantWizardOil: IconInput<Player<any>>;
export declare const DarkRune: IconInput<Player<any>>;
export declare const ElixirOfDraenicWisdom: IconInput<Player<any>>;
export declare const ElixirOfMajorFirePower: IconInput<Player<any>>;
export declare const ElixirOfMajorFrostPower: IconInput<Player<any>>;
export declare const ElixirOfMajorMageblood: IconInput<Player<any>>;
export declare const ElixirOfMajorShadowPower: IconInput<Player<any>>;
export declare const FlaskOfBlindingLight: IconInput<Player<any>>;
export declare const FlaskOfMightyRestoration: IconInput<Player<any>>;
export declare const FlaskOfPureDeath: IconInput<Player<any>>;
export declare const FlaskOfSupremePower: IconInput<Player<any>>;
export declare const KreegsStoutBeatdown: IconInput<Player<any>>;
export declare const SkullfishSoup: IconInput<Player<any>>;
export declare const SuperiorWizardOil: IconInput<Player<any>>;
export declare const DefaultDestructionPotion: IconInput<Player<any>>;
export declare const DefaultSuperManaPotion: IconInput<Player<any>>;
export declare const DrumsOfBattleConsume: IconInput<Player<any>>;
export declare const DrumsOfRestorationConsume: IconInput<Player<any>>;
