package main

import (
	"github.com/wowsims/tbc/sim/core/proto"
)

type ItemDeclaration struct {
	ID    int
	Specs []proto.Spec // Which specs use this item
}

// Keep these sorted alphabetically by item Name.
var ItemDeclarations = []ItemDeclaration{
	{ /** A'dal's Gift */ ID: 31461, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Adornment of Stolen Souls */ ID: 28762, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Amani Punisher */ ID: 33283, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Ameer's Impulse Taser */ ID: 30011, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Amulet of Unfettered Magics */ ID: 34204, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Amulet of Vek'nilash */ ID: 21608, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Anchorite's Robe */ ID: 29129, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Ancient Spellcloak of the Highborne */ ID: 30735, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Anetheron's Noose */ ID: 30888, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Anger-Spark Gloves */ ID: 30725, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Antonidas's Aegis of Rapt Concentration */ ID: 30909, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Arcanium Signet Bands */ ID: 27746, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Ashyen's Gift */ ID: 29172, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Auchenai Anchorite's Robe */ ID: 29341, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Auchenai Staff */ ID: 29130, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Avalanche Leggings */ ID: 33533, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Baba's Cloak of Arcanistry */ ID: 28269, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Band of Al'ar */ ID: 29922, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Band of Crimson Fury */ ID: 28793, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Band of Dominion */ ID: 31290, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Band of Eternity */ ID: 29302, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Band of Frigid Elements */ ID: 32779, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Band of the Eternal Sage */ ID: 29305, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Band of the Guardian */ ID: 29320, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Band of the Inevitable */ ID: 23031, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Bands of Nefarious Deeds */ ID: 28515, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Bands of Negation */ ID: 29240, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Bands of the Coming Storm */ ID: 32259, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Belt of Blasting */ ID: 30038, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Belt of Depravity */ ID: 29241, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Belt of Divine Inspiration */ ID: 28799, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Belt of the Crescent Moon */ ID: 30914, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Big Bad Wolf's Head */ ID: 28583, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Blackwhelp Belt */ ID: 31513, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Bleeding Hollow Warhammer */ ID: 27741, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Blind-Seers Icon */ ID: 32361, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Blood-cursed Shoulderpads */ ID: 32338, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Bloodfire Greatstaff */ ID: 28188, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Blue Suede Shoes */ ID: 30894, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Boots of Blasphemy */ ID: 29242, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Boots of Blasting */ ID: 30037, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Boots of Ethereal Manipulation */ ID: 29258, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Boots of Foretelling */ ID: 28517, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Boots of Oceanic Fury */ ID: 32242, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Boots of the Infernal Coven */ ID: 28670, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Boots of the Nexus Warden */ ID: 30519, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Botanist's Gloves of Growth */ ID: 32328, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Bracers of Havok */ ID: 24250, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Bracers of Nimble Thought */ ID: 32586, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Breeches of the Occultist */ ID: 30531, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Brooch of Heightened Potential */ ID: 28134, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Brooch of Nature's Mercy */ ID: 33281, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Brooch of Unquenchable Fury */ ID: 28530, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Brute Cloak of the Ogre-Magi */ ID: 28797, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Cataclysm Chestpiece (Tier 5) */ ID: 30169, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Cataclysm Handgrips (Tier 5) */ ID: 30170, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Cataclysm Headpiece (Tier 5) */ ID: 30171, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Cataclysm Leggings (Tier 5) */ ID: 30172, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Cataclysm Shoulderpads (Tier 5) */ ID: 30173, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Chain Links of the Tumultuous Storm */ ID: 34186, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Chain of the Twilight Owl */ ID: 24121, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Charlotte's Ivy */ ID: 31338, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Chestguard of Relentless Storms */ ID: 32592, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Chronicle of Dark Secrets */ ID: 30872, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Circlet of the Starcaller */ ID: 30297, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Cloak of Entropy */ ID: 31140, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Cloak of Woven Energy */ ID: 29813, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Cloak of the Black Void */ ID: 24252, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Cloak of the Illidari Council */ ID: 32331, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Cloak of the Necropolis */ ID: 23050, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Cobalt Band of Tyrigosa */ ID: 29352, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Cord of Screaming Terrors */ ID: 30064, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Cowl of Gul'dan */ ID: 34332, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Cowl of the Grand Engineer */ ID: 29986, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Cowl of the Illidari High Lord */ ID: 32525, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Crimson Bracers of Gloom */ ID: 27462, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Crystalweave Bracers */ ID: 32655, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Cuffs of Devastation */ ID: 30870, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Cyclone Chestguard (Tier 4) */ ID: 29033, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Cyclone Faceguard (Tier 4) */ ID: 29035, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Cyclone Handguards (Tier 4) */ ID: 29034, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Cyclone Legguards (Tier 4) */ ID: 29036, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Cyclone Shoulderguards (Tier 4) */ ID: 29037, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Dark Iron Smoking Pipe */ ID: 38290, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Darkmoon Card: Crusade */ ID: 31856, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Draenei Honor Guard Shield */ ID: 31287, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Dragonheart Flameshield */ ID: 28611, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Dreamcrystal Band */ ID: 32664, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Earth Mantle Handwraps */ ID: 27793, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Earthbreaker's Greaves */ ID: 29313, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Elekk Hide Spaulders */ ID: 31797, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Elunite Empowered Bracers */ ID: 32351, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Erupting Epaulets */ ID: 34390, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Essence of the Martyr */ ID: 29376, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Eternium Runed Blade */ ID: 23554, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Evoker's Mark of the Redemption */ ID: 31075, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Exorcist's Mail Helm */ ID: 28758, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Extravagant Boots of Malice */ ID: 27821, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Eye of Magtheridon */ ID: 28789, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Eye of the Night */ ID: 24116, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Eyestalk Waist Cord */ ID: 22730, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Fathom-Brooch of the Tidewalker */ ID: 30663, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** FathomStone */ ID: 30049, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Fetish of the Primal Gods */ ID: 33334, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Figurine - Living Ruby Serpent */ ID: 24126, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Flashfire Girdle */ ID: 32276, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Focused Mana Bindings */ ID: 32270, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Footpads of Madness */ ID: 33357, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Gadgetstorm Goggles */ ID: 32476, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Garments of Crashing Shores */ ID: 34396, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Gauntlets of the Ancient Shadowmoon */ ID: 34350, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Gauntlets of the Sun King */ ID: 29987, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Gavel of Unearthed Secrets */ ID: 30832, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Gem of Trapped Innocents */ ID: 23057, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** General's Mail Bracers */ ID: 28638, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** General's Mail Girdle */ ID: 28639, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** General's Mail Sabatons */ ID: 28640, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Girdle of Living Flame */ ID: 27743, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Girdle of Ruination */ ID: 24256, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Gladiator's Endgame */ ID: 28346, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Gladiator's Gavel / Gladiator's Spellblade */ ID: 28297, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Gladiator's Mail Armor */ ID: 27469, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Gladiator's Mail Gauntlets */ ID: 27470, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Gladiator's Mail Helm */ ID: 27471, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Gladiator's Mail Leggings */ ID: 27472, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Gladiator's Mail Spaulders */ ID: 27473, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Gladiator's War Staff */ ID: 24557, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Glider's Sabatons of Nature's Wrath */ ID: 30682, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Gloves of Oblivion */ ID: 27537, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Gloves of Pandemonium */ ID: 31149, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Gloves of the Deadwatcher */ ID: 27493, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Gloves of the High Magus */ ID: 30924, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Grand Scepter of the Nexus-Kings */ ID: 27842, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Grips of Nature's Wrath */ ID: 33534, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Hammer of Judgement */ ID: 34009, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Handguards of Defiled Worlds */ ID: 34344, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Handwraps of Flowing Thought */ ID: 28507, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Haramad's Leggings of the Third Coin */ ID: 29343, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Harmony's Touch */ ID: 29784, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Hatefury Mantle */ ID: 30884, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Hauberk of the Furious Elements */ ID: 33965, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Heart of the Pit */ ID: 34179, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Hex Shrunken Head */ ID: 33829, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Hood of Oblivion */ ID: 28415, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Hortus' Seal of Brilliance */ ID: 27534, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Hurricane Boots */ ID: 30043, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Hydra-fang Necklace */ ID: 27758, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Icon of the Silver Crescent */ ID: 29370, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Illidari Runeshield */ ID: 34011, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Illidari Shoulderpads */ ID: 30079, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Incanter's Cowl */ ID: 28278, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Incanter's Gloves */ ID: 27508, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Incanter's Robe */ ID: 28229, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Incanter's Trousers */ ID: 27838, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Jewel of Infinite Possibilities */ ID: 28734, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Karaborian Talisman */ ID: 28781, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Khadgar's Kilt of Abjuration */ ID: 28185, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Khadgar's Knapsack */ ID: 29273, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Kirin Tor Master's Trousers */ ID: 30532, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Kurenai Kilt */ ID: 29142, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Lamp of Peaceful Radiance */ ID: 28412, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Landing Boots */ ID: 30004, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Leggings of Channeled Elements */ ID: 30916, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Leggings of Devastation */ ID: 32367, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Leggings of Elemental Fury */ ID: 23665, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Leggings of Polarity */ ID: 23070, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Leggings of the Seventh Circle */ ID: 30734, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Leggings of the Third Coin */ ID: 29314, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Lightning Crown */ ID: 31330, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Lola's Eve */ ID: 31339, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Loop of Cursed Bones */ ID: 33466, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Loop of Forged Power */ ID: 34362, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Lurker's Belt of Nature's Wrath */ ID: 30677, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Mag'hari Ritualist's Horns */ ID: 28169, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Mage-Collar of the Firestorm */ ID: 27488, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Magma Plume Boots */ ID: 27845, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Malefic Girdle */ ID: 28654, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Mana Infused Wristguards */ ID: 29955, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Mana-Etched Crown */ ID: 28193, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Mana-Etched Gloves */ ID: 27465, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Mana-Etched Pantaloons */ ID: 27907, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Mana-Etched Spaulders */ ID: 27796, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Mana-Etched Vestments */ ID: 28191, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Manacles of Rememberance */ ID: 25778, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Manastorm Band */ ID: 30366, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Manasurge Pendant */ ID: 29368, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Mantle of Nimble Thought */ ID: 32587, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Mantle of Three Terrors */ ID: 27994, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Mantle of the Elven Kings */ ID: 30024, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Mantle of the Mind Flayer */ ID: 28726, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Manual of the Nethermancer */ ID: 28260, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Mark of the Champion */ ID: 23207, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Mask of Inner Fire */ ID: 27993, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Mazthoril Honor Shield */ ID: 29268, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Merciless Gladiator's Gavel / Spellblade */ ID: 32963, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Mindstorm Wristbands */ ID: 29918, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Molten Earth Kilt */ ID: 28266, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Monsoon Belt */ ID: 30044, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Moonchild Leggings */ ID: 27492, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Mooncrest Headdress */ ID: 30946, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Moonrage Girdle */ ID: 27783, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Moonstrider Boots */ ID: 27914, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Natasha's Arcane Filament */ ID: 31693, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Natasha's Ember Necklace */ ID: 31692, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Nathrezim Mindblade */ ID: 28770, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Natural Alignment Crystal */ ID: 19344, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Naturewarden's Treads */ ID: 32352, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Neltharion's Tear */ ID: 19379, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Nethershard Girdle */ ID: 28565, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Netherstrike Belt */ ID: 29520, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Netherstrike Bracers */ ID: 29521, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Netherstrike Breastplate */ ID: 29519, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Ogre Slayer's Cover */ ID: 25777, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Omor's Unyielding Will */ ID: 27464, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Pantaloons of Flaming Wrath */ ID: 30709, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Pauldrons of Elemental Fury */ ID: 23664, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Pauldrons of Wild Magic */ ID: 32078, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Pauldrons of the Furious Elements */ ID: 33970, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Pendant of Dominance */ ID: 28245, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Pendant of Sunfire */ ID: 34359, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Pendant of the Lost Ages */ ID: 30008, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Quagmirran's Eye */ ID: 27683, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Ravager's Bands of Nature's Wrath */ ID: 30686, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Ring of Ancient Knowledge */ ID: 32527, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Ring of Captured Storms */ ID: 32247, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Ring of Conflict Survival */ ID: 31922, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Ring of Cryptic Dreams */ ID: 29367, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Ring of Endless Coils */ ID: 30109, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Ring of Omnipotence */ ID: 34230, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Ring of Recurrence */ ID: 28753, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Ring of Unrelenting Storms */ ID: 30667, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Ring of the Fallen God */ ID: 21709, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Robe of Hateful Echoes */ ID: 30056, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Robe of Oblivion */ ID: 28232, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Robe of the Crimson Order */ ID: 31297, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Robe of the Elder Scribes */ ID: 28602, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Robe of the Great Dark Beyond */ ID: 27824, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Robe of the Shadow Council */ ID: 32327, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Robes of Rhonin */ ID: 30913, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Royal Cloak of the Sunstriders */ ID: 29992, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Ruby Drape of the Mysticant */ ID: 28766, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Ruby Slippers */ ID: 28585, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Runed Spell-Cuffs */ ID: 33588, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Runesong Dagger */ ID: 27868, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Ryngo's Band of Ingenuity */ ID: 28394, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Sapphiron's Left Eye */ ID: 23049, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Sash of Arcane Visions */ ID: 29257, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Sash of Sealed Fate */ ID: 31283, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Sash of Serpentra */ ID: 27795, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Scintillating Coral Band */ ID: 27784, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Scryer's Bloodgem */ ID: 29132, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Seal of the Damned */ ID: 23025, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Seal of the Exorcist */ ID: 28555, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Seer's Signet */ ID: 29126, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Sergeant's Heavy Cape */ ID: 28379, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Sethekk Oracle Cloak */ ID: 27981, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Sextant of Unstable Currents */ ID: 30626, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Shadow-Cloak of Dalaran */ ID: 28570, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Shadowcaster's Drape */ ID: 33591, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Shamanistic Helmet of Second Sight */ ID: 31107, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Shattrath Jumpers */ ID: 28179, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Shattrath Wraps */ ID: 28174, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Shawl of Shifting Probabilities */ ID: 29369, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Shiffar's Nexus-Horn */ ID: 28418, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Shifting Naaru Sliver */ ID: 34429, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Shimmering Azure Boots */ ID: 29808, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Shroud of the Highborne */ ID: 32524, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Sigil-Laced Boots */ ID: 28406, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Silvermoon Crest Shield */ ID: 27910, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Sky Breaker */ ID: 27937, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Skycall Totem */ ID: 33506, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Skyshatter Bands */ ID: 34437, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Skyshatter Breastplate (Tier 6) */ ID: 31017, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Skyshatter Cord */ ID: 34542, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Skyshatter Gauntlets (Tier 6) */ ID: 31008, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Skyshatter Headguard (Tier 6) */ ID: 31014, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Skyshatter Legguards (Tier 6) */ ID: 31020, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Skyshatter Mantle (Tier 6) */ ID: 31023, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Skyshatter Treads */ ID: 34566, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Slippers of the Seacaller */ ID: 32239, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Sorcerer's Alchemist Stone */ ID: 35749, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Soul-Eater's Handwraps */ ID: 28780, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Sparking Arcanite Ring */ ID: 28227, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Spaulders of Oblivion */ ID: 27778, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Spaulders of the Torn-heart */ ID: 30925, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Spectral Band of Innervation */ ID: 28510, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Spellbreaker's Buckler */ ID: 30984, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Spellstrike Hood */ ID: 24266, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Spellstrike Pants */ ID: 24262, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Staff of Infinite Mysteries */ ID: 28633, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Star-Heart Lamp */ ID: 28187, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Starlight Dagger */ ID: 27543, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Starlight Gauntlets */ ID: 24452, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Storm Master's Helmet */ ID: 32086, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Stormsong Kilt */ ID: 30541, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Sunflare */ ID: 34336, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Talisman of Nightbane */ ID: 28603, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Talon of the Tempest */ ID: 30723, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Tattered Cape of Antonidas */ ID: 34242, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Tempest Leggings */ ID: 29141, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Tempest's Touch */ ID: 29317, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Terokk's Shadowstaff */ ID: 29355, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Terokk's Wisdom */ ID: 32541, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** The Bringer of Death */ ID: 31308, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** The Lightning Capacitor */ ID: 28785, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** The Maelstrom's Fury */ ID: 32237, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** The Nexus Key */ ID: 29988, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** The Restrained Essence of Sapphiron */ ID: 23046, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** The Saga of Terokk */ ID: 29330, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** The Skull of Gul'dan */ ID: 32483, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** The Sun King's Talisman */ ID: 30015, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Thundercaller's Gauntlets */ ID: 31280, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Tidefury Chestpiece */ ID: 28231, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Tidefury Gauntlets */ ID: 27510, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Tidefury Helm */ ID: 28349, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Tidefury Kilt */ ID: 27909, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Tidefury Shoulderguards */ ID: 27802, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Torc of the Sethekk Prophet */ ID: 29333, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Totem of Ancestral Guidance */ ID: 32330, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Totem of the Pulsing Earth */ ID: 29389, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Totem of the Storm */ ID: 23199, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Totem of the Void */ ID: 28248, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Translucent Spellthread Necklace */ ID: 32349, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Treads of Booming Thunder */ ID: 33537, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Trial-Fire Trousers */ ID: 28594, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Trousers of Oblivion */ ID: 27948, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Trousers of the Astromancer */ ID: 29972, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Uni-Mind Headdress */ ID: 28744, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Velvet Boots of the Guardian */ ID: 30067, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Vestments of the Sea-Witch */ ID: 30107, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Veteran's Mail Bracers */ ID: 32817, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Veteran's Mail Sabatons */ ID: 32792, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Violet Signet (H) */ ID: 29285, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Violet Signet (R) */ ID: 29286, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Violet Signet of the Archmage */ ID: 29287, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Waistwrap of Infinity */ ID: 32256, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Warp Engineer's Prismatic Chain */ ID: 28254, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Warp Infused Drape */ ID: 28342, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Warpstaff of Arcanum */ ID: 28341, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Wave-Crest Striders */ ID: 29245, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Wave-Fury Vambraces */ ID: 29243, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Wave-Song Girdle */ ID: 29244, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Wicked Witch's Hat */ ID: 28586, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Will of Edward the Odd */ ID: 31340, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Windhawk Belt */ ID: 29524, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Windhawk Bracers */ ID: 29523, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Windhawk Hauberk */ ID: 29522, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Windscale Hood */ ID: 29504, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Windshear Boots */ ID: 28810, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** World's End Bracers */ ID: 27522, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Worldfire Chestguard */ ID: 28391, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Wub's Cursed Hexblade */ ID: 33354, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Xi'ri's Gift */ ID: 29179, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Yor's Collapsing Band */ ID: 31921, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
	{ /** Zhar'doom, Greatstaff of the Devourer */ ID: 32374, Specs: []proto.Spec{proto.Spec_SpecElementalShaman}},
}
