package main

import (
	"github.com/wowsims/tbc/sim/core/proto"
)

type ItemDeclaration struct {
	ID         int
	Categories []proto.ItemCategory // Which categories this item belongs to.
}

// Keep these sorted alphabetically by item Name.
var ItemDeclarations = []ItemDeclaration{
	{ /** A'dal's Gift */ ID: 31461, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Adornment of Stolen Souls */ ID: 28762, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Amani Punisher */ ID: 33283, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Ameer's Impulse Taser */ ID: 30011, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Amulet of Unfettered Magics */ ID: 34204, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Amulet of Vek'nilash */ ID: 21608, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Anchorite's Robe */ ID: 29129, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Ancient Spellcloak of the Highborne */ ID: 30735, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Anetheron's Noose */ ID: 30888, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Anger-Spark Gloves */ ID: 30725, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Antonidas's Aegis of Rapt Concentration */ ID: 30909, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Arcanium Signet Bands */ ID: 27746, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Ashyen's Gift */ ID: 29172, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Auchenai Anchorite's Robe */ ID: 29341, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Auchenai Staff */ ID: 29130, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Avalanche Leggings */ ID: 33533, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Baba's Cloak of Arcanistry */ ID: 28269, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Band of Al'ar */ ID: 29922, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Band of Crimson Fury */ ID: 28793, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Band of Dominion */ ID: 31290, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Band of Eternity */ ID: 29302, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Band of Frigid Elements */ ID: 32779, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Band of the Eternal Sage */ ID: 29305, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Band of the Guardian */ ID: 29320, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Band of the Inevitable */ ID: 23031, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Bands of Nefarious Deeds */ ID: 28515, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Bands of Negation */ ID: 29240, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Bands of the Coming Storm */ ID: 32259, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Belt of Blasting */ ID: 30038, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Belt of Depravity */ ID: 29241, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Belt of Divine Inspiration */ ID: 28799, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Belt of the Crescent Moon */ ID: 30914, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Big Bad Wolf's Head */ ID: 28583, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Blackwhelp Belt */ ID: 31513, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Bleeding Hollow Warhammer */ ID: 27741, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Blind-Seers Icon */ ID: 32361, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Blood-cursed Shoulderpads */ ID: 32338, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Bloodfire Greatstaff */ ID: 28188, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Blue Suede Shoes */ ID: 30894, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Boots of Blasphemy */ ID: 29242, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Boots of Blasting */ ID: 30037, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Boots of Ethereal Manipulation */ ID: 29258, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Boots of Foretelling */ ID: 28517, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Boots of Oceanic Fury */ ID: 32242, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Boots of the Infernal Coven */ ID: 28670, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Boots of the Nexus Warden */ ID: 30519, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Botanist's Gloves of Growth */ ID: 32328, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Bracers of Havok */ ID: 24250, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Bracers of Nimble Thought */ ID: 32586, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Breeches of the Occultist */ ID: 30531, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Brooch of Heightened Potential */ ID: 28134, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Brooch of Nature's Mercy */ ID: 33281, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Brooch of Unquenchable Fury */ ID: 28530, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Brute Cloak of the Ogre-Magi */ ID: 28797, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Cataclysm Chestpiece (Tier 5) */ ID: 30169, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Cataclysm Handgrips (Tier 5) */ ID: 30170, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Cataclysm Headpiece (Tier 5) */ ID: 30171, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Cataclysm Leggings (Tier 5) */ ID: 30172, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Cataclysm Shoulderpads (Tier 5) */ ID: 30173, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Chain Links of the Tumultuous Storm */ ID: 34186, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Chain of the Twilight Owl */ ID: 24121, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Charlotte's Ivy */ ID: 31338, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Chestguard of Relentless Storms */ ID: 32592, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Chronicle of Dark Secrets */ ID: 30872, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Circlet of the Starcaller */ ID: 30297, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Cloak of Entropy */ ID: 31140, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Cloak of Woven Energy */ ID: 29813, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Cloak of the Black Void */ ID: 24252, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Cloak of the Illidari Council */ ID: 32331, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Cloak of the Necropolis */ ID: 23050, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Cobalt Band of Tyrigosa */ ID: 29352, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Cord of Screaming Terrors */ ID: 30064, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Cowl of Gul'dan */ ID: 34332, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Cowl of the Grand Engineer */ ID: 29986, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Cowl of the Illidari High Lord */ ID: 32525, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Crimson Bracers of Gloom */ ID: 27462, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Crystalweave Bracers */ ID: 32655, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Cuffs of Devastation */ ID: 30870, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Cyclone Chestguard (Tier 4) */ ID: 29033, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Cyclone Faceguard (Tier 4) */ ID: 29035, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Cyclone Handguards (Tier 4) */ ID: 29034, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Cyclone Legguards (Tier 4) */ ID: 29036, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Cyclone Shoulderguards (Tier 4) */ ID: 29037, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Dark Iron Smoking Pipe */ ID: 38290, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Darkmoon Card: Crusade */ ID: 31856, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Draenei Honor Guard Shield */ ID: 31287, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Dragonheart Flameshield */ ID: 28611, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Dreamcrystal Band */ ID: 32664, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Earth Mantle Handwraps */ ID: 27793, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Earthbreaker's Greaves */ ID: 29313, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Elekk Hide Spaulders */ ID: 31797, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Elunite Empowered Bracers */ ID: 32351, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Erupting Epaulets */ ID: 34390, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Essence of the Martyr */ ID: 29376, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Eternium Runed Blade */ ID: 23554, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Evoker's Mark of the Redemption */ ID: 31075, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Exorcist's Mail Helm */ ID: 28758, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Extravagant Boots of Malice */ ID: 27821, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Eye of Magtheridon */ ID: 28789, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Eye of the Night */ ID: 24116, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Eyestalk Waist Cord */ ID: 22730, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Fathom-Brooch of the Tidewalker */ ID: 30663, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** FathomStone */ ID: 30049, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Fetish of the Primal Gods */ ID: 33334, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Figurine - Living Ruby Serpent */ ID: 24126, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Flashfire Girdle */ ID: 32276, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Focused Mana Bindings */ ID: 32270, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Footpads of Madness */ ID: 33357, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Gadgetstorm Goggles */ ID: 32476, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Garments of Crashing Shores */ ID: 34396, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Gauntlets of the Ancient Shadowmoon */ ID: 34350, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Gauntlets of the Sun King */ ID: 29987, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Gavel of Unearthed Secrets */ ID: 30832, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Gem of Trapped Innocents */ ID: 23057, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** General's Mail Bracers */ ID: 28638, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** General's Mail Girdle */ ID: 28639, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** General's Mail Sabatons */ ID: 28640, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Girdle of Living Flame */ ID: 27743, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Girdle of Ruination */ ID: 24256, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Gladiator's Endgame */ ID: 28346, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Gladiator's Gavel / Gladiator's Spellblade */ ID: 28297, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Gladiator's Mail Armor */ ID: 27469, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Gladiator's Mail Gauntlets */ ID: 27470, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Gladiator's Mail Helm */ ID: 27471, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Gladiator's Mail Leggings */ ID: 27472, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Gladiator's Mail Spaulders */ ID: 27473, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Gladiator's War Staff */ ID: 24557, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Glider's Sabatons of Nature's Wrath */ ID: 30682, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Gloves of Oblivion */ ID: 27537, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Gloves of Pandemonium */ ID: 31149, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Gloves of the Deadwatcher */ ID: 27493, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Gloves of the High Magus */ ID: 30924, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Grand Scepter of the Nexus-Kings */ ID: 27842, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Grips of Nature's Wrath */ ID: 33534, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Hammer of Judgement */ ID: 34009, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Handguards of Defiled Worlds */ ID: 34344, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Handwraps of Flowing Thought */ ID: 28507, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Haramad's Leggings of the Third Coin */ ID: 29343, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Harmony's Touch */ ID: 29784, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Hatefury Mantle */ ID: 30884, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Hauberk of the Furious Elements */ ID: 33965, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Heart of the Pit */ ID: 34179, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Hex Shrunken Head */ ID: 33829, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Hood of Oblivion */ ID: 28415, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Hortus' Seal of Brilliance */ ID: 27534, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Hurricane Boots */ ID: 30043, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Hydra-fang Necklace */ ID: 27758, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Icon of the Silver Crescent */ ID: 29370, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Illidari Runeshield */ ID: 34011, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Illidari Shoulderpads */ ID: 30079, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Incanter's Cowl */ ID: 28278, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Incanter's Gloves */ ID: 27508, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Incanter's Robe */ ID: 28229, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Incanter's Trousers */ ID: 27838, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Jade Pendant of Blasting */ ID: 20966, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Jewel of Infinite Possibilities */ ID: 28734, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Karaborian Talisman */ ID: 28781, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Khadgar's Kilt of Abjuration */ ID: 28185, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Khadgar's Knapsack */ ID: 29273, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Kirin Tor Master's Trousers */ ID: 30532, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Kurenai Kilt */ ID: 29142, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Lamp of Peaceful Radiance */ ID: 28412, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Landing Boots */ ID: 30004, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Leggings of Channeled Elements */ ID: 30916, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Leggings of Devastation */ ID: 32367, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Leggings of Elemental Fury */ ID: 23665, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Leggings of Polarity */ ID: 23070, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Leggings of the Seventh Circle */ ID: 30734, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Leggings of the Third Coin */ ID: 29314, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Lightning Crown */ ID: 31330, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Lola's Eve */ ID: 31339, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Loop of Cursed Bones */ ID: 33466, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Loop of Forged Power */ ID: 34362, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Lurker's Belt of Nature's Wrath */ ID: 30677, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Mag'hari Ritualist's Horns */ ID: 28169, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Mage-Collar of the Firestorm */ ID: 27488, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Magma Plume Boots */ ID: 27845, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Malefic Girdle */ ID: 28654, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Mana Infused Wristguards */ ID: 29955, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Mana-Etched Crown */ ID: 28193, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Mana-Etched Gloves */ ID: 27465, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Mana-Etched Pantaloons */ ID: 27907, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Mana-Etched Spaulders */ ID: 27796, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Mana-Etched Vestments */ ID: 28191, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Manacles of Rememberance */ ID: 25778, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Manastorm Band */ ID: 30366, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Manasurge Pendant */ ID: 29368, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Mantle of Nimble Thought */ ID: 32587, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Mantle of Three Terrors */ ID: 27994, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Mantle of the Elven Kings */ ID: 30024, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Mantle of the Mind Flayer */ ID: 28726, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Manual of the Nethermancer */ ID: 28260, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Mark of the Champion */ ID: 23207, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Mask of Inner Fire */ ID: 27993, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Mazthoril Honor Shield */ ID: 29268, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Merciless Gladiator's Gavel / Spellblade */ ID: 32963, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Mindstorm Wristbands */ ID: 29918, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Molten Earth Kilt */ ID: 28266, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Monsoon Belt */ ID: 30044, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Moonchild Leggings */ ID: 27492, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Mooncrest Headdress */ ID: 30946, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Moonrage Girdle */ ID: 27783, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Moonstrider Boots */ ID: 27914, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Natasha's Arcane Filament */ ID: 31693, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Natasha's Ember Necklace */ ID: 31692, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Nathrezim Mindblade */ ID: 28770, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Natural Alignment Crystal */ ID: 19344, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Naturewarden's Treads */ ID: 32352, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Neltharion's Tear */ ID: 19379, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Nethershard Girdle */ ID: 28565, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Netherstrike Belt */ ID: 29520, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Netherstrike Bracers */ ID: 29521, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Netherstrike Breastplate */ ID: 29519, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Ogre Slayer's Cover */ ID: 25777, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Omor's Unyielding Will */ ID: 27464, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Pantaloons of Flaming Wrath */ ID: 30709, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Pauldrons of Elemental Fury */ ID: 23664, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Pauldrons of Wild Magic */ ID: 32078, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Pauldrons of the Furious Elements */ ID: 33970, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Pendant of Dominance */ ID: 28245, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Pendant of Sunfire */ ID: 34359, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Pendant of the Lost Ages */ ID: 30008, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Quagmirran's Eye */ ID: 27683, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Ravager's Bands of Nature's Wrath */ ID: 30686, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Ring of Ancient Knowledge */ ID: 32527, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Ring of Captured Storms */ ID: 32247, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Ring of Conflict Survival */ ID: 31922, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Ring of Cryptic Dreams */ ID: 29367, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Ring of Endless Coils */ ID: 30109, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Ring of Omnipotence */ ID: 34230, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Ring of Recurrence */ ID: 28753, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Ring of Unrelenting Storms */ ID: 30667, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Ring of the Fallen God */ ID: 21709, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Robe of Hateful Echoes */ ID: 30056, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Robe of Oblivion */ ID: 28232, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Robe of the Crimson Order */ ID: 31297, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Robe of the Elder Scribes */ ID: 28602, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Robe of the Great Dark Beyond */ ID: 27824, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Robe of the Shadow Council */ ID: 32327, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Robes of Rhonin */ ID: 30913, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Royal Cloak of the Sunstriders */ ID: 29992, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Ruby Drape of the Mysticant */ ID: 28766, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Ruby Slippers */ ID: 28585, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Runed Spell-Cuffs */ ID: 33588, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Runesong Dagger */ ID: 27868, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Ryngo's Band of Ingenuity */ ID: 28394, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Sapphiron's Left Eye */ ID: 23049, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Sash of Arcane Visions */ ID: 29257, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Sash of Sealed Fate */ ID: 31283, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Sash of Serpentra */ ID: 27795, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Scintillating Coral Band */ ID: 27784, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Scryer's Bloodgem */ ID: 29132, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Seal of the Damned */ ID: 23025, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Seal of the Exorcist */ ID: 28555, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Seer's Signet */ ID: 29126, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Sergeant's Heavy Cape */ ID: 28379, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Sethekk Oracle Cloak */ ID: 27981, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Sextant of Unstable Currents */ ID: 30626, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Shadow-Cloak of Dalaran */ ID: 28570, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Shadowcaster's Drape */ ID: 33591, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Shamanistic Helmet of Second Sight */ ID: 31107, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Shattrath Jumpers */ ID: 28179, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Shattrath Wraps */ ID: 28174, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Shawl of Shifting Probabilities */ ID: 29369, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Shiffar's Nexus-Horn */ ID: 28418, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Shifting Naaru Sliver */ ID: 34429, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Shimmering Azure Boots */ ID: 29808, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Shroud of the Highborne */ ID: 32524, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Sigil-Laced Boots */ ID: 28406, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Silvermoon Crest Shield */ ID: 27910, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Sky Breaker */ ID: 27937, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Skycall Totem */ ID: 33506, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Skyshatter Bands */ ID: 34437, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Skyshatter Breastplate (Tier 6) */ ID: 31017, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Skyshatter Cord */ ID: 34542, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Skyshatter Gauntlets (Tier 6) */ ID: 31008, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Skyshatter Headguard (Tier 6) */ ID: 31014, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Skyshatter Legguards (Tier 6) */ ID: 31020, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Skyshatter Mantle (Tier 6) */ ID: 31023, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Skyshatter Treads */ ID: 34566, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Slippers of the Seacaller */ ID: 32239, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Sorcerer's Alchemist Stone */ ID: 35749, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Soul-Eater's Handwraps */ ID: 28780, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Sparking Arcanite Ring */ ID: 28227, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Spaulders of Oblivion */ ID: 27778, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Spaulders of the Torn-heart */ ID: 30925, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Spectral Band of Innervation */ ID: 28510, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Spellbreaker's Buckler */ ID: 30984, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Spellstrike Hood */ ID: 24266, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Spellstrike Pants */ ID: 24262, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Staff of Infinite Mysteries */ ID: 28633, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Star-Heart Lamp */ ID: 28187, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Starlight Dagger */ ID: 27543, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Starlight Gauntlets */ ID: 24452, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Storm Master's Helmet */ ID: 32086, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Stormsong Kilt */ ID: 30541, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Sunflare */ ID: 34336, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Talisman of Nightbane */ ID: 28603, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Talon of the Tempest */ ID: 30723, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Tattered Cape of Antonidas */ ID: 34242, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Tempest Leggings */ ID: 29141, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Tempest's Touch */ ID: 29317, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Terokk's Shadowstaff */ ID: 29355, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Terokk's Wisdom */ ID: 32541, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** The Bringer of Death */ ID: 31308, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** The Lightning Capacitor */ ID: 28785, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** The Maelstrom's Fury */ ID: 32237, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** The Nexus Key */ ID: 29988, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** The Restrained Essence of Sapphiron */ ID: 23046, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** The Saga of Terokk */ ID: 29330, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** The Skull of Gul'dan */ ID: 32483, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** The Sun King's Talisman */ ID: 30015, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Thundercaller's Gauntlets */ ID: 31280, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Tidefury Chestpiece */ ID: 28231, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Tidefury Gauntlets */ ID: 27510, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Tidefury Helm */ ID: 28349, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Tidefury Kilt */ ID: 27909, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Tidefury Shoulderguards */ ID: 27802, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Torc of the Sethekk Prophet */ ID: 29333, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Totem of Ancestral Guidance */ ID: 32330, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Totem of the Pulsing Earth */ ID: 29389, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Totem of the Storm */ ID: 23199, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Totem of the Void */ ID: 28248, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Translucent Spellthread Necklace */ ID: 32349, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Treads of Booming Thunder */ ID: 33537, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Trial-Fire Trousers */ ID: 28594, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Trousers of Oblivion */ ID: 27948, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Trousers of the Astromancer */ ID: 29972, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Uni-Mind Headdress */ ID: 28744, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Velvet Boots of the Guardian */ ID: 30067, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Vestments of the Sea-Witch */ ID: 30107, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Veteran's Mail Bracers */ ID: 32817, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Veteran's Mail Sabatons */ ID: 32792, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Violet Signet (H) */ ID: 29285, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Violet Signet (R) */ ID: 29286, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Violet Signet of the Archmage */ ID: 29287, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Waistwrap of Infinity */ ID: 32256, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Warp Engineer's Prismatic Chain */ ID: 28254, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Warp Infused Drape */ ID: 28342, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Warpstaff of Arcanum */ ID: 28341, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Wave-Crest Striders */ ID: 29245, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Wave-Fury Vambraces */ ID: 29243, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Wave-Song Girdle */ ID: 29244, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Wicked Witch's Hat */ ID: 28586, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Will of Edward the Odd */ ID: 31340, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Windhawk Belt */ ID: 29524, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Windhawk Bracers */ ID: 29523, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Windhawk Hauberk */ ID: 29522, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Windscale Hood */ ID: 29504, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Windshear Boots */ ID: 28810, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** World's End Bracers */ ID: 27522, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Worldfire Chestguard */ ID: 28391, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Wub's Cursed Hexblade */ ID: 33354, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Xi'ri's Gift */ ID: 29179, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Yor's Collapsing Band */ ID: 31921, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
	{ /** Zhar'doom, Greatstaff of the Devourer */ ID: 32374, Categories: []proto.ItemCategory{proto.ItemCategory_ItemCategoryCaster}},
}
