name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: 3.x

      - name: Install Protoc Go plugin
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Build 🔧
        run: |
          npm install
          make

      - name: Test
        run: |
          make test
          make dist

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
            repository-name: wowsims/pages-deploy
            branch: main
            folder: dist/tbc
            target-folder: tbc
            single-commit: true
            token: ${{ secrets.DEPLOY_REPO_TOKEN }}
            clean: false
